# Generated by Django 5.2.1 on 2025-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
