# Generated by Django 5.2.1 on 2025-07-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.pedido'),
        ),
    ]
