# Generated by Django 5.2.1 on 2025-07-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('carritoproductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_en_carrito', to='carrito.carrito'),
        ),
    ]
